/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseNavbar: typeof import('./src/components/BaseNavbar.vue')['default']
    CardWithOffcanvas: typeof import('./src/components/common/CardWithOffcanvas.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    DailyConsumptionChart: typeof import('./src/components/DailyConsumptionChart.vue')['default']
    DailyConsumptionSummary: typeof import('./src/components/summaries/DailyConsumptionSummary.vue')['default']
    DailyGastoChart: typeof import('./src/components/DailyGastoChart.vue')['default']
    DailyGastoSummary: typeof import('./src/components/summaries/DailyGastoSummary.vue')['default']
    DateRangeSelector: typeof import('./src/components/DateRangeSelector.vue')['default']
    JsonImporter: typeof import('./src/components/JsonImporter.vue')['default']
    MonthlyConsumptionChart: typeof import('./src/components/MonthlyConsumptionChart.vue')['default']
    MonthlyConsumptionSummary: typeof import('./src/components/summaries/MonthlyConsumptionSummary.vue')['default']
    MonthlyGastoChart: typeof import('./src/components/MonthlyGastoChart.vue')['default']
    MonthlyGastoSummary: typeof import('./src/components/summaries/MonthlyGastoSummary.vue')['default']
    MonthlyHourlyConsumptionChart: typeof import('./src/components/MonthlyHourlyConsumptionChart.vue')['default']
    MonthlyHourlyConsumptionSummary: typeof import('./src/components/summaries/MonthlyHourlyConsumptionSummary.vue')['default']
    MonthlyHourlyGastoChart: typeof import('./src/components/MonthlyHourlyGastoChart.vue')['default']
    MonthlyHourlyGastoSummary: typeof import('./src/components/summaries/MonthlyHourlyGastoSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
    TotalGasto: typeof import('./src/components/TotalGasto.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VFileInput: typeof import('vuetify/components')['VFileInput']
    VIcon: typeof import('vuetify/components')['VIcon']
    VLayout: typeof import('vuetify/components')['VLayout']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VOverlay: typeof import('vuetify/components')['VOverlay']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VToolbar: typeof import('vuetify/components')['VToolbar']
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle']
  }
}
