/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseNavbar: typeof import('./src/components/BaseNavbar.vue')['default']
    DailyConsumptionChart: typeof import('./src/components/DailyConsumptionChart.vue')['default']
    DateRangeSelector: typeof import('./src/components/DateRangeSelector.vue')['default']
    JsonImporter: typeof import('./src/components/JsonImporter.vue')['default']
    MonthlyConsumptionChart: typeof import('./src/components/MonthlyConsumptionChart.vue')['default']
    MonthlyHourlyConsumptionChart: typeof import('./src/components/MonthlyHourlyConsumptionChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
    TotalGasto: typeof import('./src/components/TotalGasto.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VFileInput: typeof import('vuetify/components')['VFileInput']
    VIcon: typeof import('vuetify/components')['VIcon']
    VLayout: typeof import('vuetify/components')['VLayout']
    VMain: typeof import('vuetify/components')['VMain']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
  }
}
